# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/dual/cs5190661/vivado/assignment10/assignment10.cache/wt [current_project]
set_property parent.project_path /home/dual/cs5190661/vivado/assignment10/assignment10.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/dual/cs5190661/vivado/assignment10/assignment10.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet /home/dual/cs5190661/vivado/assignment10/assignment10.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files /home/dual/cs5190661/vivado/assignment10/assignment10.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp]
read_vhdl -library xil_defaultlib {
  /home/dual/cs5190661/vivado/assignment10/assignment10.srcs/sources_1/imports/vivado/assignment9/assignment9.srcs/sources_1/imports/new/singlessd.vhd
  /home/dual/cs5190661/vivado/assignment10/assignment10.srcs/sources_1/imports/vivado/assignment9/assignment9.srcs/sources_1/imports/new/display.vhd
  /home/dual/cs5190661/vivado/assignment10/assignment10.srcs/sources_1/imports/vivado/2019CS10375_2019CS50661_8/trans.vhd
  /home/dual/cs5190661/vivado/assignment10/assignment10.srcs/sources_1/imports/vivado/2019CS10375_2019CS50661_8/rec.vhd
  /home/dual/cs5190661/vivado/assignment10/assignment10.srcs/sources_1/imports/vivado/assignment9/assignment9.srcs/sources_1/new/btn_debouncer.vhd
  /home/dual/cs5190661/vivado/assignment10/assignment10.srcs/sources_1/imports/vivado/assignment9/assignment9.srcs/sources_1/new/bram.vhd
  /home/dual/cs5190661/vivado/assignment10/assignment10.srcs/sources_1/new/master.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/dual/cs5190661/vivado/assignment10/assignment10.srcs/constrs_1/imports/Downloads/Basys-3-Master.xdc
set_property used_in_implementation false [get_files /home/dual/cs5190661/vivado/assignment10/assignment10.srcs/constrs_1/imports/Downloads/Basys-3-Master.xdc]


synth_design -top master -part xc7a35tcpg236-1


write_checkpoint -force -noxdef master.dcp

catch { report_utilization -file master_utilization_synth.rpt -pb master_utilization_synth.pb }
